### ISSUE TITLE
All links have 500's when clicked from 

### ISSUE THREAD

**Issue by sursh** [sursh/blaggregator#78]
@punchagan Links to view blog posts works great from blaggregator.us, but ALL links are broken when coming from Zulip. I'm at the end of my time allotted to work on this today so I haven't looked at this in detail. Going to roll back now. 

Here is a portion of the logs—I believe this is 1.5 of these errors. It's a little hard to tell since Heroku doesn't record | display logs in order. 

```
2015-03-08T23:02:10.017844+00:00 app[web.1]: Traceback (most recent call last):
2015-03-08T23:02:10.017838+00:00 app[web.1]: Internal Server Error: /post/ThNclE/view
2015-03-08T23:02:10.017850+00:00 app[web.1]:   File "/app/home/views.py", line 60, in view_post
2015-03-08T23:02:10.017848+00:00 app[web.1]:     response = callback(request, *callback_args, **callback_kwargs)
2015-03-08T23:02:10.017854+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/manager.py", line 149, in create
2015-03-08T23:02:10.017859+00:00 app[web.1]:     obj.save(force_insert=True, using=self.db)
2015-03-08T23:02:10.017852+00:00 app[web.1]:     user_agent=request.META.get('HTTP_USER_AGENT', None),
2015-03-08T23:02:10.017855+00:00 app[web.1]:     return self.get_query_set().create(**kwargs)
2015-03-08T23:02:10.017862+00:00 app[web.1]:     force_update=force_update, update_fields=update_fields)
2015-03-08T23:02:10.017873+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 937, in execute_sql
2015-03-08T23:02:10.017867+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/manager.py", line 215, in _insert
2015-03-08T23:02:10.017863+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/base.py", line 650, in save_base
2015-03-08T23:02:10.017872+00:00 app[web.1]:     return query.get_compiler(using=using).execute_sql(return_id)
2015-03-08T23:02:10.017870+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/query.py", line 1661, in insert_query
2015-03-08T23:02:10.017846+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
2015-03-08T23:02:10.017878+00:00 app[web.1]:     six.reraise(utils.IntegrityError, utils.IntegrityError(*tuple(e.args)), sys.exc_info()[2])
2015-03-08T23:02:10.017865+00:00 app[web.1]:     result = manager._insert([self], fields=fields, return_id=update_pk, using=using, raw=raw)
2015-03-08T23:02:10.017875+00:00 app[web.1]:     cursor.execute(sql, params)
2015-03-08T23:02:10.017876+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 56, in execute
2015-03-08T23:02:10.017885+00:00 app[web.1]: DETAIL:  Failing row contains (29, 6677, 2015-03-08 23:02:10.010438+00, null, 10.123.66.198, Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.3...).
2015-03-08T23:02:10.017869+00:00 app[web.1]:     return insert_query(self.model, objs, fields, **kwargs)
2015-03-08T23:02:10.017883+00:00 app[web.1]: IntegrityError: null value in column "referer" violates not-null constraint
2015-03-08T23:02:10.017860+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/base.py", line 546, in save
2015-03-08T23:02:10.017881+00:00 app[web.1]:     return self.cursor.execute(query, args)
2015-03-08T23:02:10.017886+00:00 app[web.1]: 
2015-03-08T23:02:10.017880+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 54, in execute
2015-03-08T23:02:20.749020+00:00 heroku[router]: at=info method=GET path="/post/UHZQQj/view" host=www.blaggregator.us request_id=53f98df7-cb9f-400e-a04a-00e6ea1dd86b fwd="24.193.114.250" dyno=web.1 connect=1ms service=60ms status=500 bytes=225
2015-03-08T23:02:20.744323+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
2015-03-08T23:02:20.744330+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/manager.py", line 149, in create
2015-03-08T23:02:20.744333+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/query.py", line 402, in create
2015-03-08T23:02:20.744339+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/base.py", line 650, in save_base
2015-03-08T23:02:20.744342+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/manager.py", line 215, in _insert
2015-03-08T23:02:20.744349+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 937, in execute_sql
2015-03-08T23:02:20.744353+00:00 app[web.1]:     six.reraise(utils.IntegrityError, utils.IntegrityError(*tuple(e.args)), sys.exc_info()[2])
2015-03-08T23:02:20.744356+00:00 app[web.1]:     return self.cursor.execute(query, args)
2015-03-08T23:02:20.744358+00:00 app[web.1]: IntegrityError: null value in column "referer" violates not-null constraint
2015-03-08T23:02:20.744332+00:00 app[web.1]:     return self.get_query_set().create(**kwargs)
2015-03-08T23:02:20.744328+00:00 app[web.1]:     user_agent=request.META.get('HTTP_USER_AGENT', None),
2015-03-08T23:02:20.744335+00:00 app[web.1]:     obj.save(force_insert=True, using=self.db)
2015-03-08T23:02:20.744338+00:00 app[web.1]:     force_update=force_update, update_fields=update_fields)
2015-03-08T23:02:20.744341+00:00 app[web.1]:     result = manager._insert([self], fields=fields, return_id=update_pk, using=using, raw=raw)
2015-03-08T23:02:20.744346+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/query.py", line 1661, in insert_query
2015-03-08T23:02:20.744301+00:00 app[web.1]: Internal Server Error: /post/UHZQQj/view
2015-03-08T23:02:20.744306+00:00 app[web.1]: Traceback (most recent call last):
2015-03-08T23:02:20.744360+00:00 app[web.1]: DETAIL:  Failing row contains (30, 6593, 2015-03-08 23:02:20.735531+00, null, 10.123.66.198, Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.3...).
2015-03-08T23:02:20.744325+00:00 app[web.1]:     response = callback(request, *callback_args, **callback_kwargs)
2015-03-08T23:02:20.744327+00:00 app[web.1]:   File "/app/home/views.py", line 60, in view_post
2015-03-08T23:02:20.744344+00:00 app[web.1]:     return insert_query(self.model, objs, fields, **kwargs)
2015-03-08T23:02:20.744336+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/base.py", line 546, in save
2015-03-08T23:02:20.744350+00:00 app[web.1]:     cursor.execute(sql, params)
2015-03-08T23:02:20.744347+00:00 app[web.1]:     return query.get_compiler(using=using).execute_sql(return_id)
2015-03-08T23:02:20.744361+00:00 app[web.1]: 
2015-03-08T23:02:20.744352+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 56, in execute
2015-03-08T23:02:20.744355+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 54, in execute

**Comment by sursh** [comment]
ok @punchagan I've rolled back the production app to be as it was before I started working today. (This also takes out @nnja's PR temporarily...fyi)

I'm not sure why it's throwing an intergrity error...could have sworn you allowed blank for that field. Also why is the referrer blank from zulip? strange. 

Ideas?

**Comment by nnja** [comment]
Also, keep in mind my patch was submitted in December - that's also the last time I tested it. :)

**Comment by punchagan** [comment]
I feel bad for not being online while you were working on this!  Will take a look at try to fix it.
